web_system/relacionamentos/urls.py
from django.urls import path
from relacionamentos.views.funcoes import primeira_view, saudacao, calculo, exercicio, nome
from relacionamentos.views import PrimeiraView, NomeView, SaudacaoView, ReporterListView, ReporterDetailView, ReporterCreateView, ReporterGenerateCode, ReporterUpdateView, ReporterDeletelView
from relacionamentos.views.reporter import reporter_list, reporter_detail, reporter_delete, reporter_code, reporter_create, reporter_update
from relacionamentos.views.reporter_generic import *

app_name = 'relacionamentos'

urlpatterns = [
    
     path('funcao/teste', primeira_view,
          name='primeira_view'),
     
     path('funcao/saudacao', saudacao,
          name="saudacao"),

     path('funcao/exercicio/calculo/<int:x>/<int:y>', calculo,
          name="calculo"),
     
     path('funcao/exercicio/<str:nome>', exercicio,
          name='exercicio'),

     # Qualquer coisa em string, deve sempre ser por ultimo para nao inutilizar as urls de cima que sao fixas
     # nome é a variavel que vai armazenar o que vem depois de funcao/
     path('funcao/<str:nome>', nome,
          name="nome"),
     path("reporter/generic_class/list", ReporterGenericListView.as_view(), name="reporter_generic_class_list"),

    # Como esta em generic use sempre pk
     path("reporter/generic_class/read/<int:pk>/", ReporterGenericDetailView.as_view(), name="reporter_generic_class_read"),

     path("reporter/generic_class/delete/<int:pk>/", ReporterGenericDeleteView.as_view(), name="reporter_generic_class_delete"),

     path("reporter/generic_class/update/<int:pk>/", ReporterGenericUpdateView.as_view(), name="reporter_generic_class_update"),

     path("reporter/generic_class/create", ReporterGenericCreateView.as_view(), name="reporter_generic_class_create"),

     path('reporter/function/read/<int:pk>', reporter_detail, name="reporter_read"), 
     
     path('reporter/function/create/', reporter_create, name="reporter_create"),
     
     path('reporter/function/delete/<int:pk>', reporter_delete, name="reporter_delete"), 

     path('reporter/function/update/<int:reporter_id>', reporter_update, name="reporter_update" ),

     path("reporter/function/gerar_codigo/<int:reporter_id>", reporter_code, name="reporter_generate_code"),

     path('reporter/function/', reporter_list, name="reporter"), 

     path('reporter/classe/', ReporterListView.as_view(), name="reporter_view_list" ),
     
     path('reporter/classe/create/', ReporterCreateView.as_view(), name="reporter_view_create"),

     path("reporter/classe/gerar_codigo/<int:pk>", ReporterGenerateCode.as_view(), name="reporter_view_generate_code"),
     
     path('reporter/classe/update/<int:pk>', ReporterUpdateView.as_view(), name="reporter_view_update" ),
          
     path('reporter/classe/read/<int:pk>', ReporterDetailView.as_view(), name="reporter_view_read"), 

     path('reporter/classe/delete/<int:pk>', ReporterDeletelView.as_view(), name="reporter_view_delete"), 

     path('classe/teste/', PrimeiraView.as_view(), name="primeira_view_class"),
     
     path('classe/saudacao/', SaudacaoView.as_view(), name="saudacao_view_class"),

     path('classe/<str:nome>', NomeView.as_view(), name="nome_view_class" ),



]

web_system/services/urls.py
from django.urls import path
from services.views import *
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token
from services.views.reporter import ReporterListService

app_name = 'services'

# router = routers.DefaultRouter()
urlpatterns = [
    path('', api_root, name="api-root"),
    path('saudacao', saudacao, name="saudacao"),
    path('saudacao/classe', ExemploSaudacao.as_view(), name="saudacao_classe"),
    path('calculo',calculo, name="calculo"),
    path('reporter', ReporterListService.as_view(), name='reporter_list'),

]

web_system/web_system/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from web_system import views
from django.contrib.auth import views as auth_views
from web_system.forms import CustomLoginForm
from web_system.views.profile import ProfileView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('relacionamentos/', include('relacionamentos.urls', namespace="relacionamentos")),
    path('', views.estaticas.index, name="index"),
    path('funcao/contato/', views.contact, name="function_contact"),
    #path('funcao/search/', views.buscar, name="search_function"),
    path('class/contato/', views.ContactView.as_view(), name="class_contact"),
    path('accounts/login/', auth_views.LoginView.as_view(template_name="accounts/login.html", authentication_form=CustomLoginForm)),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/profile/', ProfileView.as_view(), name='profile'),
    path('services/',include('services.urls')),
]

web_system/relacionamentos/models/base.py
from django.db import models

class Base(models.Model):
    class Meta:
        abstract = True
        app_label = 'relacionamentos'

web_system/relacionamentos/models/reporter.py
from django.db import models
from .base import Base
from django.utils.translation import gettext_lazy as _
from django.core.validators import MaxLengthValidator
from ..validators.validar_cpf import valida_cpf
from ..managers.reporter_manager import ReporterManager


class Reporter(Base): 

    name = models.CharField(max_length=100,
                            verbose_name=_("Name"), 
                            help_text=_("Digite o nome do reporter"))
    
    email = models.EmailField(max_length=100,
                              verbose_name=_("Email"),
                              help_text=_("Digite o email do reporter"))
    
    cod = models.CharField(max_length=100,
                           verbose_name=_("Código"),
                           help_text=_("Informe um codigo aleatorio"),
                           default="")
    
    cpf = models.CharField(max_length=11, 
                           verbose_name=_("CPF"),
                           help_text='Digite o CPF do reporter',
                           validators=[MaxLengthValidator(11), valida_cpf],
                           unique=True)

    objects = ReporterManager()

    # Adicionar uma Permissao personalizada

    class Meta:
        # Permissoes devem seguir -> permissao_model
        permissions = [
            ("generate_code_reporter", "Pode gerar codigo para reporter"),
        ]

    def __str__(self):
        return f"{self.name} - {self.cpf}"

web_system/relacionamentos/forms/base_form.py
from django.forms import ModelForm

class BaseForm(ModelForm):
    def __init__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)
        for new_field in self.visible_fields():
            new_field.field.widget.attrs.update({"class":"form-control"})
            if len(new_field.errors.data) > 0:
                new_field.field.widget.attrs.update({"class": "form-control is-invalid"})

web_system/relacionamentos/forms/reporter.py
from .base_form import BaseForm
from ..models import Reporter

class ReporterForm(BaseForm):
    class Meta:
        model = Reporter
        fields = '__all__'

web_system/relacionamentos/views/funcoes.py
from django.shortcuts import render, redirect, HttpResponse
from django.core import serializers
from django.http import JsonResponse
from django.core.serializers import serialize
from datetime import datetime
from django.views import View
from ..models.reporter import Reporter

def primeira_view(request):
    mensagem = "Bom dia Dev I"
    return render(request, "primeira.html",{"mensagem":mensagem})

def saudacao(request):
    agora = datetime.now()
    mensagem = "boa noite"
    if 12 > agora.hour > 6:
        mensagem ="bom dia"
    elif 0 < agora.hour <=6:
        mensagem = "boa madrugada"

    #completo = f"<html><body><h1>{mensagem.capitalize()}  visitante!<br /> {agora}</h1>{request.META["REMOTE_ADDR"]}</body></html>"
    return render(request, "saudacao.html", {"mensagem":f"{mensagem.capitalize()} visistante! ","agora":f"{agora}", "user":f"{request.META["REMOTE_ADDR"]}"})

def nome(request, nome):
    reporter = Reporter.objects.find_by_name(nome)
    objeto = serializers.serialize('python', reporter)
    return JsonResponse(objeto, safe=False)
    #return HttpResponse(reporter, status=200)

def exercicio(request, nome):
    nome_original = nome
    nome_cripto = ""
    tabela = {
        "a": "4",
        "e": "3",
        "i": "1",
        "o": "0",
        "u": "v",
    }
    nome_cripto = "".join(tabela.get(l.lower(), l) for l in nome)
    return HttpResponse(f"{nome_original} - {nome_cripto}")

def calculo(request,x,y):
    operacoes =  {"soma":x+y,
                  "subtracao":x-y,
                  "multiplicacao":x*y,
                  "divisao":x/y if y != 0 else "Erro, divisao por 0",}
    return JsonResponse(operacoes)
    

web_system/relacionamentos/views/nome.py
from django.http import HttpResponse, JsonResponse
from django.views import View
from ..models import Reporter
from django.core import serializers


class NomeView(View):
    @staticmethod
    def get(request,nome):
        if nome == "" or nome == "":
            exemplos = list(Reporter.objects.all())
        else:
            exemplos = Reporter.objects.find_by_name(nome)

        tipo = str(request.GET.get("type"))
        saida = ""
        
        match tipo.lower():
            case "http":
                for exemplo in exemplos:
                    saida += f"<p><b>ID: </b> {exemplo.id}</p>"
                    saida += f"<p><b>Email: </b> {exemplo.email}</p>"
                    saida += f"<p><b>CPF: </b> {exemplo.cpf}</p>"
        
                return HttpResponse(saida, status=200)
            
            case "json":
                objeto = serializers.serialize('python', exemplos)
                return JsonResponse(objeto, safe=False)
            
            case _:
                return HttpResponse("Bad request", status=400)
            

web_system/relacionamentos/views/primeira.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views import View
class PrimeiraView(View):
    @staticmethod
    def get(request):
        mensagem = request.META["REMOTE_ADDR"]
        #return HttpResponse(mensagem, status=200)
        return render(request, "primeira.html", {"mensagem":mensagem})  

web_system/relacionamentos/views/reporter.py
import random
import string
from ..models.reporter import Reporter
from django.shortcuts import get_object_or_404, render, redirect
from ..forms.reporter import ReporterForm
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import permission_required, login_required

@login_required
@permission_required("relacionamentos.view_reporter", raise_exception=True)
@require_http_methods(['GET',])
def reporter_list(request):
    reporters = Reporter.objects.all()
    context = {"reporters":reporters}
    return render(request, "reporter/list.html", context) 

@require_http_methods(['GET', 'POST'])
def reporter_detail(request,pk):    
    reporter = Reporter.objects.get(id=pk)
    context = {"reporter":reporter}
    return render(request, "reporter/read.html", context)


@require_http_methods(['GET', 'POST'])
def reporter_create(request):
    if request.method == "POST":
        form = ReporterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('relacionamentos:reporter')
    else:
        form = ReporterForm()
    context = {
        'form':form
    }
    return render(request, 'reporter/create.html', context)

@require_http_methods(['GET', 'POST'])
def reporter_delete(request,pk):    
    reporter = get_object_or_404(Reporter, pk=pk)
    try:
        if request.method == "POST":
            v_reporter_id = request.POST.get("reporter_id",None)
            if int(v_reporter_id) == reporter.id:
                reporter.delete()
                return redirect('relacionamentos:reporter')
        else:
            context ={'reporter': reporter}
    except Exception as e:
        print(e)
        context = {}
        return render(request, "reporter/list.html", context) 

    return render(request, "reporter/delete.html", context)

@require_http_methods(['GET', 'POST'])
def reporter_code(request, reporter_id):
    reporter = get_object_or_404(Reporter, pk=reporter_id)
    try:
        letters = string.ascii_letters +string.digits
        reporter.cod = "".join(random.choice(letters) for i in range(10))
        reporter.save()
        return redirect('relacionamentos:reporter')
    except:
        print(f"Erro ao gerar código para reporter {reporter}")
        return redirect('relacionamentos:reporter')

@require_http_methods(['GET', 'POST'])
def reporter_update(request, reporter_id):
    reporter = get_object_or_404(Reporter, pk=reporter_id)
    if request.method == "POST":
        form = ReporterForm(request.POST, instance=reporter)
        if form.is_valid():
            form.save()
            return redirect('relacionamentos:reporter')
    else:
        form = ReporterForm(instance=reporter)
    context = {
        'form': form,
        'reporter': reporter,
    }
    return render(request, 'reporter/update.html', context)

web_system/relacionamentos/views/reporter_classe.py
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import get_object_or_404, render, redirect
from ..models.reporter import Reporter
from ..forms.reporter import ReporterForm
import random
import string


class ReporterListView(View):
    @staticmethod
    def get(request):
        reporters = Reporter.objects.all()
        context = {"reporters":reporters}
        return render(request, "reporter_classe/list.html", context) 
    
class ReporterDetailView(View):
    @staticmethod
    def get(request,pk):
        reporter = Reporter.objects.get(id=pk)
        context = {"reporter":reporter}
        return render(request, "reporter_classe/read.html", context)
    
class ReporterCreateView(View):
    @staticmethod
    def get(request):
        form = ReporterForm()
        context = {
            'form':form
        }
        return render(request, 'reporter_classe/create.html', context)
    
    @staticmethod
    def post(request):
        form = ReporterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('relacionamentos:reporter_view_list')
        context = {
            'form':form
        }
        return render(request, 'reporter_classe/create.html', context)


class ReporterGenerateCode(LoginRequiredMixin,  PermissionRequiredMixin, View ):
    login_url = 'accounts:login'
    permission_required = 'relacionamentos.generate_code_reporter'
    @staticmethod
    def get(request, pk):
        reporter = get_object_or_404(Reporter, pk=pk)
        try:
            letters = string.ascii_letters +string.digits
            reporter.cod = "".join(random.choice(letters) for i in range(10))
            reporter.save()
            return redirect('relacionamentos:reporter_view_generate_code')
        except:
            print(f"Erro ao gerar código para reporter {reporter}")
            return redirect('relacionamentos:reporter')
        
class ReporterUpdateView(View):
    @staticmethod
    def get(request, pk):
        reporter = get_object_or_404(Reporter, pk=pk)
        form = ReporterForm(instance=reporter)
        context = {
            'form': form,
            'reporter': reporter,
        }
        return render(request, 'reporter_classe/update.html', context)

    @staticmethod
    def post(request,pk):
        reporter = get_object_or_404(Reporter, pk=pk)
        form = ReporterForm(request.POST, instance=reporter)
        if form.is_valid():
            form.save()
            return redirect('relacionamentos:reporter')

class ReporterDeletelView(View):
    @staticmethod
    def get(request, pk):
        reporter = get_object_or_404(Reporter, pk=pk)
        try:
            context ={'reporter': reporter}
            return render(request, 'reporter_classe/delete.html', context)
        except Exception as e:
            print(e)
            context = {}
            return render(request, "reporter_classe/list.html", context) 
    @staticmethod
    def post(request,pk):
        reporter = get_object_or_404(Reporter, pk=pk)
        try:
            v_reporter_id = request.POST.get("reporter_id",None)
            if int(v_reporter_id) == pk:
                reporter.delete()
                return redirect('relacionamentos:reporter_view_list')
        except Exception as e:
            print(e)
            context = {}
            return render(request, "reporter_classe/list.html", context) 

web_system/relacionamentos/views/saudacao.py
from datetime import datetime
from django.shortcuts import render
from django.views import View
class SaudacaoView(View):
    @staticmethod
    def get(request):
        agora = datetime.now()
        mensagem = "boa noite"
        if 12 > agora.hour > 6:
            mensagem ="bom dia"
        elif 0 < agora.hour <=6:
            mensagem = "boa madrugada"

        #completo = f"<html><body><h1>{mensagem.capitalize()}  visitante!<br /> {agora}</h1>{request.META["REMOTE_ADDR"]}</body></html>"
        return render(request, "saudacao.html", {"mensagem":f"{mensagem.capitalize()} visistante! ","agora":f"{agora}", "user":f"{request.META["REMOTE_ADDR"]}"})

web_system/relacionamentos/templates/reporter/create.html
{% extends "base.html" %}

{% block title %}
 <h1>Criar Reporter</h1>
{% endblock title %}

{% block content %}
   <form action="{% url "relacionamentos:reporter_create" %}" id="reporter" method="post">
    {% csrf_token %}
    <!--{{form.as_div}} -->
    {% for field in form %}
      <div class="mb-3 text-start">
         {{ field.label_tag }} {{ field }}
         {% if field.hep_text %}
            <div class="form-text">{{ field.help_text|safe }}</div>
         {% endif %}
         <div class="invalid-feedback">{{ field.erros }}</div>
      </div>
    {% endfor %}
    <div class="mt-2">
       <button type="submit" class="btn btn-success" form="reporter" value="salvar"><i class="bi bi-floppy"></i> Salvar</button>
       <button type="reset" form="reporter" class="btn btn-secondary" value="reset"><i class="bi bi-arrow-clockwise"></i> Limpar</button>
       <a href="{% url "relacionamentos:reporter" %}" class="btn btn-light" role="button"><i class="bi bi-arrow-left"></i> Voltar</a>
      </div>
   </form>
{% endblock content %}

web_system/relacionamentos/templates/reporter/delete.html
{% extends 'base.html' %}

{% block title %}
    <h1>{{reporter.name}}</h1>
{% endblock title %}
{% block content %}
    <div class="content">
        <div class="row">
            <strong>Código:</strong>
            <p>{{reporter.id}}</p>
            <strong>Nome:</strong>
            <p>{{reporter.name}}</p>
        </div>
    </div>
    <strong>AÇÃO IRREVERSIVEL</strong>
    <p>Você realmente quer fazer a deleção?</p>
    <form id="reporter" action="{% url "relacionamentos:reporter_delete" reporter.id %}" method="post">
        {% csrf_token %}
        <input type="hidden" id="reporter_id" name="reporter_id" value="{{reporter.id}}">
        <button type="submit" class="btn btn-danger" form="reporter" value="Deletar">
            <i class="bi bi-trash"></i> Sim, Deletar
        </button>        
        <a class='btn btn-secondary bi-arrow-left' href="{% url 'relacionamentos:reporter' %}"> Voltar</a>
    </form>
{% endblock content %}

web_system/relacionamentos/templates/reporter/list.html
{% extends 'base.html' %}

{% block title %}
    {% if reporters %}
    <h1>Lista de Reporters</h1>
    {% else %}
    <h1>Nenhum Reporter encontrado</h1>
    {% endif %}
    {% endblock title %}
{% block content %}
    {% if perms.relacionamentos.add_reporter %}     
    <a href="{% url "relacionamentos:reporter_create" %}" class="btn btn-primary" role="button" title="Criar com Funções" >
        <i class="bi bi-plus-square"></i> Criar com Funções
    </a>
    {% endif %}
    {% if perms.relacionamentos.add_reporter %}     
        <a href="{% url "relacionamentos:reporter_view_create" %}" class="btn btn-info" role="button" title="Criar com Classes">
            <i class="bi bi-plus-square"></i> Criar com Classes
        </a>

        {% endif  %}
    {% if reporters %}   
    <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Nome</th>
            <th scope="col">Código</th>
            <th scope="col">Email</th>
            <th scope="col">CPF</th>
            <th scope="col">Funções</th>
            <th scope="col">Classes</th>
          </tr>
        </thead>
        <tbody>
            {% for reporter in reporters %}
            <tr>
                <th scope="row">{{ reporter.id }}</th>
                <td>{{reporter.name}}</td>
                <td>{{reporter.cod}}</td>
                <td>{{reporter.email}}</td>
                <td>{{reporter.cpf}}</td>
                <td>
                    <div>
                        {% if  perms.relacionamentos.view_reporter %} 
                            <a class="btn btn-outline-primary btn-lg" role="button" data-bs-toggle="tooltip" data-bs-placement="top" title="Detalhar" href="{% url 'relacionamentos:reporter_read' reporter.id %}"><i class="bi bi-card-list"></i></a>
                        {% endif %}
                        {% if  perms.relacionamentos.change_reporter %} 
                            <a class="btn btn-outline-success btn-lg" role="button" data-bs-toggle="tooltip" data-bs-placement="top" title="Atualizar" href="{% url 'relacionamentos:reporter_update' reporter.id %}"><i class="bi  bi-pencil"></i></a>
                        {% endif %}
                        {% if  perms.relacionamentos.generate_code_reporter %} 
                            <a class="btn btn-outline-warning btn-lg" role="button" data-bs-toggle="tooltip" data-bs-placement="top" title="Gerar código" href="{% url 'relacionamentos:reporter_generate_code' reporter.id %}"><i class="bi bi-repeat"></i></a>
                        {% endif %}
                        {% if  perms.relacionamentos.delete_reporter %} 
                            <a class="btn btn-outline-danger btn-lg" role="button" data-bs-toggle="tooltip" data-bs-placement="top" title="Deletar" href="{% url 'relacionamentos:reporter_delete' reporter.id %}"><i class="bi bi-trash"></i></a>
                        {% endif %}
                    </div>
                </td>
                <td>
                    <div>
                        {% if  perms.relacionamentos.view_reporter %} 
                            <a class="btn btn-outline-primary btn-lg" role="button" data-bs-toggle="tooltip" data-bs-placement="top" title="Detalhar" href="{% url 'relacionamentos:reporter_view_read' reporter.id %}"><i class="bi bi-card-list"></i></a>                    
                        {% endif %}
                        {% if  perms.relacionamentos.change_reporter %}
                            <a class="btn btn-outline-success btn-lg" role="button" data-bs-toggle="tooltip" data-bs-placement="top" title="Atualizar" href="{% url "relacionamentos:reporter_view_update" reporter.id %}"><i class="bi  bi-pencil"></i></a>
                        {% endif %}
                        {% if  perms.relacionamentos.generate_code_reporter %}     
                            <a class="btn btn-outline-warning btn-lg" role="button" data-bs-toggle="tooltip" data-bs-placement="top" title="Gerar código" href="{% url "relacionamentos:reporter_view_generate_code" reporter.id %}"><i class="bi bi-repeat"></i></a>
                        {% endif %}    
                        {% if  perms.relacionamentos.delete_reporter %} 
                            <a class="btn btn-outline-danger btn-lg" role="button" data-bs-toggle="tooltip" data-bs-placement="top" title="Deletar" href="{% url "relacionamentos:reporter_view_delete" reporter.id %}"><i class="bi bi-trash"></i></a>
                        {% endif %}    
                        </div>
                </td>
            </tr>
            {% endfor %}
        </tbody>
      </table>
    {% endif %}


{% endblock content %}

web_system/relacionamentos/templates/reporter/read.html
{% extends 'base.html' %}

{% block title %}
    <h1>{{reporter.name}}</h1>
{% endblock title %}
{% block content %}
    <div class="content">
        <div class="row row-cols-2">
            <div class="col border border-light-subtle text-start">
                <strong>ID:</strong>
                <span>{{reporter.id}}</span>
            </div>
            <div class="col border  border-light-subtle text-start">
                <strong>Código:</strong>
                <span>{{reporter.cod}}</span>
            </div>
       
            <div class="col border  border-light-subtle text-start">
                <strong>Nome:</strong>
                <span>{{reporter.name}}</span>
            </div>
            <div class="col border  border-light-subtle text-start">
                <strong>Email:</strong>
                <span>{{reporter.email}}</span>
            </div>
            <div class="col-12 border  border-light-subtle text-center">
                <strong>CPF:</strong>
                <span>{{reporter.cpf}}</span>
            </div>
        </div>
    </div>
    <a class='btn btn-primary bi-arrow-left mt-3' href="{% url 'relacionamentos:reporter' %}"> Voltar</a>
{% endblock content %}

web_system/relacionamentos/templates/reporter/update.html
{% extends "base.html" %}

{% block title %}
 <h1>Atualizar Reporter</h1>
{% endblock title %}

{% block content %}
   <form action="{% url "relacionamentos:reporter_update" reporter.id %}" id="reporter" method="post">
    {% csrf_token %}
    {% for field in form %}
      <div class="mb-3 text-start">
         {{ field.label_tag }} {{ field }}
         {% if field.hep_text %}
            <div class="form-text">{{ field.help_text|safe }}</div>
         {% endif %}
         <div class="invalid-feedback">{{ field.erros }}</div>
      </div>
    {% endfor %}
    <div class="mt-2">
       <button type="submit" class="btn btn-success" form="reporter" value="salvar"><i class="bi bi-floppy"></i> Salvar</button>
       <button type="reset" form="reporter" class="btn btn-secondary" value="reset"><i class="bi bi-arrow-clockwise"></i> Limpar</button>
       <a href="{% url "relacionamentos:reporter" %}" class="btn btn-light" role="button"><i class="bi bi-arrow-left"></i> Voltar</a>
      </div>
   </form>
{% endblock content %}