web_system/relacionamentos/urls.py
from django.urls import path
from relacionamentos.views.funcoes import primeira_view, saudacao, calculo, exercicio, nome
from relacionamentos.views import PrimeiraView, NomeView, SaudacaoView, ReporterListView, ReporterDetailView, ReporterCreateView, ReporterGenerateCode, ReporterUpdateView, ReporterDeletelView
from relacionamentos.views.reporter import reporter_list, reporter_detail, reporter_delete, reporter_code, reporter_create, reporter_update
from relacionamentos.views.reporter_generic import *

app_name = 'relacionamentos'

urlpatterns = [
    
     path('funcao/teste', primeira_view,
          name='primeira_view'),
     
     path('funcao/saudacao', saudacao,
          name="saudacao"),

     path('funcao/exercicio/calculo/<int:x>/<int:y>', calculo,
          name="calculo"),
     
     path('funcao/exercicio/<str:nome>', exercicio,
          name='exercicio'),

     # Qualquer coisa em string, deve sempre ser por ultimo para nao inutilizar as urls de cima que sao fixas
     # nome é a variavel que vai armazenar o que vem depois de funcao/
     path('funcao/<str:nome>', nome,
          name="nome"),
     path("reporter/generic_class/list", ReporterGenericListView.as_view(), name="reporter_generic_class_list"),

    # Como esta em generic use sempre pk
     path("reporter/generic_class/read/<int:pk>/", ReporterGenericDetailView.as_view(), name="reporter_generic_class_read"),

     path("reporter/generic_class/delete/<int:pk>/", ReporterGenericDeleteView.as_view(), name="reporter_generic_class_delete"),

     path("reporter/generic_class/update/<int:pk>/", ReporterGenericUpdateView.as_view(), name="reporter_generic_class_update"),

     path("reporter/generic_class/create", ReporterGenericCreateView.as_view(), name="reporter_generic_class_create"),

     path('reporter/function/read/<int:pk>', reporter_detail, name="reporter_read"), 
     
     path('reporter/function/create/', reporter_create, name="reporter_create"),
     
     path('reporter/function/delete/<int:pk>', reporter_delete, name="reporter_delete"), 

     path('reporter/function/update/<int:reporter_id>', reporter_update, name="reporter_update" ),

     path("reporter/function/gerar_codigo/<int:reporter_id>", reporter_code, name="reporter_generate_code"),

     path('reporter/function/', reporter_list, name="reporter"), 

     path('reporter/classe/', ReporterListView.as_view(), name="reporter_view_list" ),
     
     path('reporter/classe/create/', ReporterCreateView.as_view(), name="reporter_view_create"),

     path("reporter/classe/gerar_codigo/<int:pk>", ReporterGenerateCode.as_view(), name="reporter_view_generate_code"),
     
     path('reporter/classe/update/<int:pk>', ReporterUpdateView.as_view(), name="reporter_view_update" ),
          
     path('reporter/classe/read/<int:pk>', ReporterDetailView.as_view(), name="reporter_view_read"), 

     path('reporter/classe/delete/<int:pk>', ReporterDeletelView.as_view(), name="reporter_view_delete"), 

     path('classe/teste/', PrimeiraView.as_view(), name="primeira_view_class"),
     
     path('classe/saudacao/', SaudacaoView.as_view(), name="saudacao_view_class"),

     path('classe/<str:nome>', NomeView.as_view(), name="nome_view_class" ),



]

web_system/services/urls.py
from django.urls import path
from services.views import *
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token
from services.views.reporter import ReporterListService

app_name = 'services'

# router = routers.DefaultRouter()
urlpatterns = [
    path('', api_root, name="api-root"),
    path('saudacao', saudacao, name="saudacao"),
    path('saudacao/classe', ExemploSaudacao.as_view(), name="saudacao_classe"),
    path('calculo',calculo, name="calculo"),
    path('reporter', ReporterListService.as_view(), name='reporter_list'),

]

web_system/web_system/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from web_system import views
from django.contrib.auth import views as auth_views
from web_system.forms import CustomLoginForm
from web_system.views.profile import ProfileView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('relacionamentos/', include('relacionamentos.urls', namespace="relacionamentos")),
    path('', views.estaticas.index, name="index"),
    path('funcao/contato/', views.contact, name="function_contact"),
    #path('funcao/search/', views.buscar, name="search_function"),
    path('class/contato/', views.ContactView.as_view(), name="class_contact"),
    path('accounts/login/', auth_views.LoginView.as_view(template_name="accounts/login.html", authentication_form=CustomLoginForm)),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/profile/', ProfileView.as_view(), name='profile'),
    path('services/',include('services.urls')),
]

web_system/aula/models/base.py
from django.db import models


class Base(models.Model):
    
    class Meta:
        abstract = True
        app_label = 'aula'

web_system/relacionamentos/models/base.py
from django.db import models

class Base(models.Model):
    class Meta:
        abstract = True
        app_label = 'relacionamentos'

web_system/relacionamentos/forms/base_form.py
from django.forms import ModelForm

class BaseForm(ModelForm):
    def __init__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)
        for new_field in self.visible_fields():
            new_field.field.widget.attrs.update({"class":"form-control"})
            if len(new_field.errors.data) > 0:
                new_field.field.widget.attrs.update({"class": "form-control is-invalid"})

web_system/relacionamentos/views/primeira.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views import View
class PrimeiraView(View):
    @staticmethod
    def get(request):
        mensagem = request.META["REMOTE_ADDR"]
        #return HttpResponse(mensagem, status=200)
        return render(request, "primeira.html", {"mensagem":mensagem})  

web_system/relacionamentos/views/saudacao.py
from datetime import datetime
from django.shortcuts import render
from django.views import View
class SaudacaoView(View):
    @staticmethod
    def get(request):
        agora = datetime.now()
        mensagem = "boa noite"
        if 12 > agora.hour > 6:
            mensagem ="bom dia"
        elif 0 < agora.hour <=6:
            mensagem = "boa madrugada"

        #completo = f"<html><body><h1>{mensagem.capitalize()}  visitante!<br /> {agora}</h1>{request.META["REMOTE_ADDR"]}</body></html>"
        return render(request, "saudacao.html", {"mensagem":f"{mensagem.capitalize()} visistante! ","agora":f"{agora}", "user":f"{request.META["REMOTE_ADDR"]}"})

web_system/templates/base.html
{% extends "menu.html" %}

{% block main %}
    <div class="mt-3 mb-3">
        {% block title %}
            <h1>Título</h1>
        {% endblock title %}
    </div>
    <div class="mt-3 mb-3">
        {% block content %}
            <h2>Conteúdo</h1>
        {% endblock content %}
    </div>

{% endblock main %}

web_system/templates/index.html
{% extends "base.html" %}

{% block title %}
    <h1>Página inicial</h1>
{% endblock title %}

{% block content %}
    <h2>Disciplina de Dev I</h2>
{% endblock content %}

web_system/templates/menu.html
{% extends "minimal.html" %}

{% block menu %}
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'index' %}">WebSystem DEV I</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            URLs
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'relacionamentos:primeira_view' %}">Primeira View</a></li>
            <li><a class="dropdown-item" href="{% url 'relacionamentos:saudacao' %}">Saudação</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'relacionamentos:primeira_view_class' %}">Primeira classe</a></li>
            <li><a class="dropdown-item" href="{% url 'relacionamentos:saudacao_view_class' %}">Saudacao classe</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Models
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'relacionamentos:reporter' %}">Reporters</a></li>
            <li><a class="dropdown-item" href="#">#</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">#</a></li>
            <li><a class="dropdown-item" href="#">#</a></li>
          </ul>
        </li>
      </ul>
      {% if user.is_authenticated %}
        <span class="navbar-text text-white px-2">
          <a href="{% url "profile" %}" class="nav-link">
            <i class="bi bi-person-fill"></i> {{ user.first_name }}
          </a>
        </span>
        <div class="me-2"></div>
        <form action="{% url "logout" %}" method="post">
          {% csrf_token %}
          <button class="btn btn-outline-danger" role="button" type="submit"><i class="bi bi-box-arrow-in-left"></i></button>
        </form>
      {% else %}
        <a href="{% url "login" %}" role="button" class="btn btn-outline-primary"><i class="bi bi-box-arrow-in-right"></i></a>
      {% endif %}
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"/>
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
{% endblock menu %}

web_system/templates/minimal.html
<!doctype html>
<html lang="en" data-bs-theme="dark">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Aula de DEV I</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
  </head>
  <body>
    {% block menu %}
    {% endblock menu %}
    <div class="container text-center">
      <div class="row">
        <div class="col-lg-1">
          {% block left %}
          {% endblock left %}
        </div>
        <div class="col-lg-10">
          {% block main %}
          {% endblock main %}
        </div>
        <div class="col-lg-1">
          {% block right %}
          {% endblock right %}
        </div>
      </div>
      {% block additional_lines %}
      {% endblock additional_lines %}
    </div>
    <div class="container">
      <footer class="navbar navbar-inverse d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top navbar-fixed-bottom">
        <div class="col-md-4 d-flex align-items-center">
          <a href="/" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
            <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
          </a>
          <span class="mb-3 mb-md-0 text-body-secondary">© {% now "Y" %} Aula de DEV I</span>
        </div>

        <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
          <li class="ms-3"><a class="text-body-secondary" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"></use></svg></a></li>
          <li class="ms-3"><a class="text-body-secondary" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"></use></svg></a></li>
          <li class="ms-3"><a class="text-body-secondary" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"></use></svg></a></li>
        </ul>
      </footer>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
      <script>
        var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
        var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
          return new bootstrap.Tooltip(tooltipTriggerEl)
        })
  </script>
  </body>
</html>

web_system/templates/primeira.html
{% extends "base.html" %}

{% block title %}
 <h2>{{mensagem}}</h2>
{% endblock title %}

{% block content %}
   
{% endblock content %}

web_system/templates/saudacao.html
{% extends "base.html" %}

{% block title %}
    <h1>{{mensagem}}</h1>
{% endblock title %}

{% block content %}
    <h2>Agora: {{agora}}</h2>
    <p>{{user}}</p>
{% endblock content %}